bumblebee.version = 0.0.1

bumblebee.mqttConfig.tcpPort=1883
bumblebee.mqttConfig.hostname=0.0.0.0
bumblebee.mqttConfig.storeClass=bumblebee.mqtt.store.InMemoryStore

bumblebee.securityConfig.authManagerClass=bumblebee.security.file.AuthManager