bumblebee.version = 0.0.1

bumblebee.mqttConfig.tcpPort=1883
bumblebee.mqttConfig.hostname=0.0.0.0
bumblebee.mqttConfig.onEventWorkers[0]=bumblebee.mqtt.worker.tinyflux.OnEventWorker

bumblebee.mqttConfig.storeClass=bumblebee.mqtt.store.InMemoryStore

bumblebee.securityConfig.authManagerClass=bumblebee.security.file.AuthManager

# Do not use the same client id in prod
bumblebee.securityConfig.users[0].userId=bb_91b3cc65
bumblebee.securityConfig.users[0].userName=bumblebee
bumblebee.securityConfig.users[0].role.name=superadmin
bumblebee.securityConfig.users[0].role.description=super admin
bumblebee.securityConfig.users[0].role.acl[0].scope=#
bumblebee.securityConfig.users[0].role.acl[0].permission=update
bumblebee.securityConfig.users[0].role.acl[0].type=1
bumblebee.securityConfig.users[0].role.acl[1].scope=#
bumblebee.securityConfig.users[0].role.acl[1].permission=update
bumblebee.securityConfig.users[0].role.acl[1].type=2
# Do not use the same password in prod (test)
bumblebee.securityConfig.users[0].password=$2a$10$7kQGobpxS.TKOhFfEJRj4OWVLNM2Is2zOLbuxRmwPFF9YaY/PJ1My

bumblebee.workerConfig.tinyFluxConfig.organization=bumblebee

bumblebee.workerConfig.payloadLoggingConfig.path=.bumblebee
